-- SQL Dump of AE_backup_3ewes.mdb
-- generated by MDB Viewer 2.3.1
-- optimized for MySQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS `Members`;

CREATE TABLE `Members` (
    `MEMBER_ID` INTEGER PRIMARY KEY,
    `ORDER_NO` INTEGER,
    `MemberNo` INTEGER,
    `ORDER_TYPE` VARCHAR(1),
    `HouseAddress` VARCHAR(90),
    `ORDER_DATE` DATETIME,
    `NationalNo` VARCHAR(12),
    `Cvlid` VARCHAR(12),
    `FNAME` VARCHAR(15),
    `SNAME` VARCHAR(15),
    `TNAME` VARCHAR(15),
    `FORNAME` VARCHAR(15),
    `ZFAM_NAME` VARCHAR(50),
    `BIRTH_DATE` DATETIME,
    `ACCEPTED` BOOLEAN,
    `RESPONS` VARCHAR(12),
    `Sponsor` INTEGER,
    `StudyDegree` VARCHAR(30),
    `employee` VARCHAR(30),
    `JobTel` VARCHAR(7),
    `JobAddress` VARCHAR(40),
    `HouseTel` VARCHAR(7),
    `ZSTATUS` INTEGER,
    `LstPayDate` DATETIME,
    `LstPayDoc` VARCHAR(12),
    `DOC_DATE` DATETIME,
    `DOC_NO` VARCHAR(8),
    `MeetingDate` DATETIME,
    `MeetingNumber` INTEGER,
    `Sponsership` BOOLEAN
) CHARACTER SET 'UTF8';

